# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.


#DEFAULT VALUES BEFORE SECRETS YML CONFIG
# development:
#   secret_key_base: e5124683b58f341c20f43e84f0f9d08fbee40fdc2d5d5e406188e902009f66f702339bf6ac5902e84c5204526c0d8cc87e0fe8cde99e3723b58a963656695fd8
#
# test:
#   secret_key_base: ec5c0fcbf54ecae46b059f993286f4d44144449931986b1fc661fae5c59c1a6976cc651c071a1e6f19bb142bca92f8b61e01a789ad7881f4138074b85157ca58

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>



development:
  secret_key_base: 9aaeadaf3347e5748cfccab62052771ced98ec6faca1caab5c2f1614a69d8f3a6bc77471da0d177f7395380f4af684798e77d2a3346a534cc938cc05e7fb3826
  URL: 'https://kteam:draewjUgbksIjcv19epwhpkcpnzieqkn@159.8.53.13:443'
  PEM: |
    -----BEGIN CERTIFICATE-----
    MIIGFzCCA/+gAwIBAgIJAPh5ydn3+FCeMA0GCSqGSIb3DQEBBQUAMIGhMQswCQYD
    VQQGEwJHUjEPMA0GA1UECAwGQXR0aWNhMQ8wDQYDVQQHDAZBdGhlbnMxHTAbBgNV
    BAoMFENyeXB0ZWlhIE5ldHdvcmtzIFNBMQ8wDQYDVQQLDAZEZXZPcHMxFDASBgNV
    BAMMCzE1OS44LjUzLjEzMSowKAYJKoZIhvcNAQkBFhtkZXZvcHNAY3J5cHRlaWFu
    ZXR3b3Jrcy5jb20wHhcNMTcwNTEyMTExNzM0WhcNMTgwNTEyMTExNzM0WjCBoTEL
    MAkGA1UEBhMCR1IxDzANBgNVBAgMBkF0dGljYTEPMA0GA1UEBwwGQXRoZW5zMR0w
    GwYDVQQKDBRDcnlwdGVpYSBOZXR3b3JrcyBTQTEPMA0GA1UECwwGRGV2T3BzMRQw
    EgYDVQQDDAsxNTkuOC41My4xMzEqMCgGCSqGSIb3DQEJARYbZGV2b3BzQGNyeXB0
    ZWlhbmV0d29ya3MuY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
    qxMoWc+uGFr9l3e5kexcMIC8HoqsEtzVEho7aHo0/hyvRgn6XFjvZjGjHzvUv9oL
    wxjUj5M8Oz/oPE6B7Yzlxt/bi1698UvheaiGX5pY076pFUA5yS8um2qr77HsuK+J
    XaiFjAsfh9lOMyST55akNfH9SkyehTYMyTafvhyKNAlN4kKt2W5FLSCVJjRZXGnb
    yzcF6oxIQhxZg8zYroV9k8chJIxWNQ6VrI4aDd9Hn+Uuan/6CKV6KDnL9pHHoB21
    A6E/vFTZTEG3jJvu2zhO70NXNV1iC23ie/28MGESKM3RqLQhYJ08MhxmmsZEdBMG
    +LVAL4lV9hLA5hnYLv1ojemq3mtdBtb448UklePChlPK5JCwVyxcDdu7PVyZfoPe
    Id2e5JHs8aMP2SzAqcxKu/XsND+aowpZyzUTJsgBNWqXcPFZPIJI3Kinzv5t8p7c
    /yvBHjngnShQhRu9X1C5ZXAoPMf3W9wy4qduHeMpw9FfZO22tywlzIzaQnP7epGZ
    YYRJvi2YptBowIRMQsgzEXfmDeIUVBzdg2ZZRa8l5xZuNZyEyPhkCqcYqtXqgYFf
    w/OKOnuyOtCyqjMCszHcgQo0rdfqAmtklMTU3pQUkW2u9yS8eU5NPFzvecE0xkmg
    ATF82/SLI8acTvbym0p/pyXMsWH/fN4ECwhN/Vg8hXkCAwEAAaNQME4wHQYDVR0O
    BBYEFHCqCguOwcV0Se4TUt0ZrNy8dD/jMB8GA1UdIwQYMBaAFHCqCguOwcV0Se4T
    Ut0ZrNy8dD/jMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggIBAEWFc/ca
    v7EVDaEZ3dL5y1q7R8T5Yy6SV04Isdsh5Q933OUncP5PIxKbD0wBvai6MheVJUBf
    joM76eNmjvsJ3lfZtJXKetjxAUoFAMXhOb2WcXaut7s+XNy20uL1rc0vwjbcFkhp
    HVzPvjOREA9zh8Awp9JSt0RAH7/A1/B1d7KJLM0ypK9KkgLKW8GAbo1jGc6fWebl
    pldkoOT+oqWSkEJJhTil8PSxL5osCCykb/mvNy3Pxk+sH2N/aBdyqLJnQWXL6u3o
    MRhm5BGhdY4DLtR+7uNxJ5K/fxllF05/cq8QNPYg3EO9By9TC7/f0Srpb2OWcQsP
    P21vylJuz5ikUJl4PFf/95nYHk0xOohywkS1Bo55Xjwc4twD/VtMX4iWGU7OECDj
    dZTXKNCynOW337gnrq47prPuNg5C2/xnGBQscZ5gzLSsc+IOuqCOlu1Ko8aJm816
    zzb8KHLjgmx6Ifogk20fxUKTdlu0QXtmq6v/D7b6+hD3BJPa5ZgFqJSF+wzCf0QA
    A8qi1SHV07Z3DjG+0uduykxGUGEYdB9nBn9ZdAcZJMBmRdbEj4PZNK9A9WSiWwzJ
    be2G/F2YSb9qLT723Dgz+PcBwbWXPNcHUSidA8p1nl1sbRwKBkYd217bZf6NlbdF
    S5eaGnJfmHQRGdCI0nNLVHAjOr2Tb1dNKIxe
    -----END CERTIFICATE-----

test:
  secret_key_base: 44f1777ea73b533885adce82222f0905b0ec50ac532467846aa96ac0bdfe4bb9c582e5f4e09d99a6aabfa373d4faf81ac8a3ade16192d3672a4ab49da8e0271f
  URL: 'https://kteam:draewjUgbksIjcv19epwhpkcpnzieqkn@159.8.53.13:443'
  PEM: |
    -----BEGIN CERTIFICATE-----
    MIIGFzCCA/+gAwIBAgIJAPh5ydn3+FCeMA0GCSqGSIb3DQEBBQUAMIGhMQswCQYD
    VQQGEwJHUjEPMA0GA1UECAwGQXR0aWNhMQ8wDQYDVQQHDAZBdGhlbnMxHTAbBgNV
    BAoMFENyeXB0ZWlhIE5ldHdvcmtzIFNBMQ8wDQYDVQQLDAZEZXZPcHMxFDASBgNV
    BAMMCzE1OS44LjUzLjEzMSowKAYJKoZIhvcNAQkBFhtkZXZvcHNAY3J5cHRlaWFu
    ZXR3b3Jrcy5jb20wHhcNMTcwNTEyMTExNzM0WhcNMTgwNTEyMTExNzM0WjCBoTEL
    MAkGA1UEBhMCR1IxDzANBgNVBAgMBkF0dGljYTEPMA0GA1UEBwwGQXRoZW5zMR0w
    GwYDVQQKDBRDcnlwdGVpYSBOZXR3b3JrcyBTQTEPMA0GA1UECwwGRGV2T3BzMRQw
    EgYDVQQDDAsxNTkuOC41My4xMzEqMCgGCSqGSIb3DQEJARYbZGV2b3BzQGNyeXB0
    ZWlhbmV0d29ya3MuY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
    qxMoWc+uGFr9l3e5kexcMIC8HoqsEtzVEho7aHo0/hyvRgn6XFjvZjGjHzvUv9oL
    wxjUj5M8Oz/oPE6B7Yzlxt/bi1698UvheaiGX5pY076pFUA5yS8um2qr77HsuK+J
    XaiFjAsfh9lOMyST55akNfH9SkyehTYMyTafvhyKNAlN4kKt2W5FLSCVJjRZXGnb
    yzcF6oxIQhxZg8zYroV9k8chJIxWNQ6VrI4aDd9Hn+Uuan/6CKV6KDnL9pHHoB21
    A6E/vFTZTEG3jJvu2zhO70NXNV1iC23ie/28MGESKM3RqLQhYJ08MhxmmsZEdBMG
    +LVAL4lV9hLA5hnYLv1ojemq3mtdBtb448UklePChlPK5JCwVyxcDdu7PVyZfoPe
    Id2e5JHs8aMP2SzAqcxKu/XsND+aowpZyzUTJsgBNWqXcPFZPIJI3Kinzv5t8p7c
    /yvBHjngnShQhRu9X1C5ZXAoPMf3W9wy4qduHeMpw9FfZO22tywlzIzaQnP7epGZ
    YYRJvi2YptBowIRMQsgzEXfmDeIUVBzdg2ZZRa8l5xZuNZyEyPhkCqcYqtXqgYFf
    w/OKOnuyOtCyqjMCszHcgQo0rdfqAmtklMTU3pQUkW2u9yS8eU5NPFzvecE0xkmg
    ATF82/SLI8acTvbym0p/pyXMsWH/fN4ECwhN/Vg8hXkCAwEAAaNQME4wHQYDVR0O
    BBYEFHCqCguOwcV0Se4TUt0ZrNy8dD/jMB8GA1UdIwQYMBaAFHCqCguOwcV0Se4T
    Ut0ZrNy8dD/jMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggIBAEWFc/ca
    v7EVDaEZ3dL5y1q7R8T5Yy6SV04Isdsh5Q933OUncP5PIxKbD0wBvai6MheVJUBf
    joM76eNmjvsJ3lfZtJXKetjxAUoFAMXhOb2WcXaut7s+XNy20uL1rc0vwjbcFkhp
    HVzPvjOREA9zh8Awp9JSt0RAH7/A1/B1d7KJLM0ypK9KkgLKW8GAbo1jGc6fWebl
    pldkoOT+oqWSkEJJhTil8PSxL5osCCykb/mvNy3Pxk+sH2N/aBdyqLJnQWXL6u3o
    MRhm5BGhdY4DLtR+7uNxJ5K/fxllF05/cq8QNPYg3EO9By9TC7/f0Srpb2OWcQsP
    P21vylJuz5ikUJl4PFf/95nYHk0xOohywkS1Bo55Xjwc4twD/VtMX4iWGU7OECDj
    dZTXKNCynOW337gnrq47prPuNg5C2/xnGBQscZ5gzLSsc+IOuqCOlu1Ko8aJm816
    zzb8KHLjgmx6Ifogk20fxUKTdlu0QXtmq6v/D7b6+hD3BJPa5ZgFqJSF+wzCf0QA
    A8qi1SHV07Z3DjG+0uduykxGUGEYdB9nBn9ZdAcZJMBmRdbEj4PZNK9A9WSiWwzJ
    be2G/F2YSb9qLT723Dgz+PcBwbWXPNcHUSidA8p1nl1sbRwKBkYd217bZf6NlbdF
    S5eaGnJfmHQRGdCI0nNLVHAjOr2Tb1dNKIxe
    -----END CERTIFICATE-----


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  URL: 'https://kteam:draewjUgbksIjcv19epwhpkcpnzieqkn@159.8.53.13:443'
  PEM: |
    -----BEGIN CERTIFICATE-----
    MIIGFzCCA/+gAwIBAgIJAPh5ydn3+FCeMA0GCSqGSIb3DQEBBQUAMIGhMQswCQYD
    VQQGEwJHUjEPMA0GA1UECAwGQXR0aWNhMQ8wDQYDVQQHDAZBdGhlbnMxHTAbBgNV
    BAoMFENyeXB0ZWlhIE5ldHdvcmtzIFNBMQ8wDQYDVQQLDAZEZXZPcHMxFDASBgNV
    BAMMCzE1OS44LjUzLjEzMSowKAYJKoZIhvcNAQkBFhtkZXZvcHNAY3J5cHRlaWFu
    ZXR3b3Jrcy5jb20wHhcNMTcwNTEyMTExNzM0WhcNMTgwNTEyMTExNzM0WjCBoTEL
    MAkGA1UEBhMCR1IxDzANBgNVBAgMBkF0dGljYTEPMA0GA1UEBwwGQXRoZW5zMR0w
    GwYDVQQKDBRDcnlwdGVpYSBOZXR3b3JrcyBTQTEPMA0GA1UECwwGRGV2T3BzMRQw
    EgYDVQQDDAsxNTkuOC41My4xMzEqMCgGCSqGSIb3DQEJARYbZGV2b3BzQGNyeXB0
    ZWlhbmV0d29ya3MuY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
    qxMoWc+uGFr9l3e5kexcMIC8HoqsEtzVEho7aHo0/hyvRgn6XFjvZjGjHzvUv9oL
    wxjUj5M8Oz/oPE6B7Yzlxt/bi1698UvheaiGX5pY076pFUA5yS8um2qr77HsuK+J
    XaiFjAsfh9lOMyST55akNfH9SkyehTYMyTafvhyKNAlN4kKt2W5FLSCVJjRZXGnb
    yzcF6oxIQhxZg8zYroV9k8chJIxWNQ6VrI4aDd9Hn+Uuan/6CKV6KDnL9pHHoB21
    A6E/vFTZTEG3jJvu2zhO70NXNV1iC23ie/28MGESKM3RqLQhYJ08MhxmmsZEdBMG
    +LVAL4lV9hLA5hnYLv1ojemq3mtdBtb448UklePChlPK5JCwVyxcDdu7PVyZfoPe
    Id2e5JHs8aMP2SzAqcxKu/XsND+aowpZyzUTJsgBNWqXcPFZPIJI3Kinzv5t8p7c
    /yvBHjngnShQhRu9X1C5ZXAoPMf3W9wy4qduHeMpw9FfZO22tywlzIzaQnP7epGZ
    YYRJvi2YptBowIRMQsgzEXfmDeIUVBzdg2ZZRa8l5xZuNZyEyPhkCqcYqtXqgYFf
    w/OKOnuyOtCyqjMCszHcgQo0rdfqAmtklMTU3pQUkW2u9yS8eU5NPFzvecE0xkmg
    ATF82/SLI8acTvbym0p/pyXMsWH/fN4ECwhN/Vg8hXkCAwEAAaNQME4wHQYDVR0O
    BBYEFHCqCguOwcV0Se4TUt0ZrNy8dD/jMB8GA1UdIwQYMBaAFHCqCguOwcV0Se4T
    Ut0ZrNy8dD/jMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggIBAEWFc/ca
    v7EVDaEZ3dL5y1q7R8T5Yy6SV04Isdsh5Q933OUncP5PIxKbD0wBvai6MheVJUBf
    joM76eNmjvsJ3lfZtJXKetjxAUoFAMXhOb2WcXaut7s+XNy20uL1rc0vwjbcFkhp
    HVzPvjOREA9zh8Awp9JSt0RAH7/A1/B1d7KJLM0ypK9KkgLKW8GAbo1jGc6fWebl
    pldkoOT+oqWSkEJJhTil8PSxL5osCCykb/mvNy3Pxk+sH2N/aBdyqLJnQWXL6u3o
    MRhm5BGhdY4DLtR+7uNxJ5K/fxllF05/cq8QNPYg3EO9By9TC7/f0Srpb2OWcQsP
    P21vylJuz5ikUJl4PFf/95nYHk0xOohywkS1Bo55Xjwc4twD/VtMX4iWGU7OECDj
    dZTXKNCynOW337gnrq47prPuNg5C2/xnGBQscZ5gzLSsc+IOuqCOlu1Ko8aJm816
    zzb8KHLjgmx6Ifogk20fxUKTdlu0QXtmq6v/D7b6+hD3BJPa5ZgFqJSF+wzCf0QA
    A8qi1SHV07Z3DjG+0uduykxGUGEYdB9nBn9ZdAcZJMBmRdbEj4PZNK9A9WSiWwzJ
    be2G/F2YSb9qLT723Dgz+PcBwbWXPNcHUSidA8p1nl1sbRwKBkYd217bZf6NlbdF
    S5eaGnJfmHQRGdCI0nNLVHAjOr2Tb1dNKIxe
    -----END CERTIFICATE-----
